FROM ubuntu:18.04
LABEL maintainer="diracdiego@gmail.com"
LABEL version="1.0"

RUN apt update && apt install -y \
    software-properties-common
RUN add-apt-repository ppa:team-gcc-arm-embedded/ppa
RUN apt update && apt install -y \
    gcc-arm-embedded \
	qemu-system-arm \
	qemu-user \
	gcc-multilib-arm-linux-gnueabi \
	binutils \
	llvm \
	clang \
	gcc-multilib

CMD ["/bin/bash"]
